"""migrate

Revision ID: 5406f80bc059
Revises: d6c28323a4df
Create Date: 2023-03-10 01:32:38.933799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5406f80bc059'
down_revision = 'd6c28323a4df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoice', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_column('invoice', 'user_id')
    # ### end Alembic commands ###
