"""migrate

Revision ID: 6239d58d0889
Revises: 5406f80bc059
Create Date: 2023-03-10 11:14:20.318351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6239d58d0889'
down_revision = '5406f80bc059'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'delete')
    # ### end Alembic commands ###
