"""migrate

Revision ID: 859843818eb6
Revises: 6239d58d0889
Create Date: 2023-03-10 13:35:22.209019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859843818eb6'
down_revision = '6239d58d0889'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('currency', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'currency')
    # ### end Alembic commands ###
