"""migrate

Revision ID: bcd50b36fe52
Revises: 9163b6c2accd
Create Date: 2023-03-10 23:49:47.874716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd50b36fe52'
down_revision = '9163b6c2accd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'paid')
    # ### end Alembic commands ###
